# Generated by Django 4.1.3 on 2022-11-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_organizationabouts_organizationabout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='isactive',
            field=models.BooleanField(default='True'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
