# Generated by Django 4.1.3 on 2022-11-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_organizationabout_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='bannerimage',
            field=models.ImageField(upload_to='articles/static/articles/images/banner'),
        ),
    ]
